#!/bin/sh

# Check if the user konduit exists in the system database if not then create it
# and add /opt/konduit as it's home directory
if ! getent passwd konduit >/dev/null; then
  echo "adding user konduit:daemon"
  # Adding /opt/konduit as the home directory for the user "konduit"
  useradd -r -M -d /opt/konduit -s /sbin/nologin -c "konduit Daemon" konduit
fi

mkdir -p /opt/konduit/serving
mkdir -p /var/log/konduit/serving
chown -R konduit:konduit /opt/konduit
chown -R konduit:konduit /var/log/konduit/serving
chmod -R 755 /opt/konduit
chmod -R 755 /var/log/konduit/serving

exit 0