// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-service.proto

package ai.konduit.serving.vertx.protocols.grpc.api;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.konduit.serving.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errorCode = 1;</code>
   */
  java.lang.String getErrorCode();
  /**
   * <code>string errorCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>string errorMessage = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
