// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-service.proto

package ai.konduit.serving.vertx.protocols.grpc.api;

public final class GrpcService {
  private GrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_konduit_serving_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ai_konduit_serving_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022grpc-service.proto\022\022ai.konduit.serving" +
      "\0323ai/konduit/serving/pipeline/api/protob" +
      "uf/data.proto\"8\n\rErrorResponse\022\021\n\terrorC" +
      "ode\030\001 \001(\t\022\024\n\014errorMessage\030\002 \001(\t2R\n\003Api\022K" +
      "\n\007predict\022\036.ai.konduit.serving.DataSchem" +
      "e\032\036.ai.konduit.serving.DataScheme\"\000B<\n+a" +
      "i.konduit.serving.vertx.protocols.grpc.a" +
      "piB\013GrpcServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.konduit.serving.pipeline.impl.data.protobuf.DataProtoMessage.getDescriptor(),
        }, assigner);
    internal_static_ai_konduit_serving_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ai_konduit_serving_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ai_konduit_serving_ErrorResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", });
    ai.konduit.serving.pipeline.impl.data.protobuf.DataProtoMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
