// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-service.proto

package ai.konduit.serving.vertx.protocols.grpc.api;

public final class GrpcService {
  private GrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022grpc-service.proto\022\022ai.konduit.serving" +
      "\0323ai/konduit/serving/pipeline/api/protob" +
      "uf/data.proto2X\n\tInference\022K\n\007predict\022\036." +
      "ai.konduit.serving.DataScheme\032\036.ai.kondu" +
      "it.serving.DataScheme\"\000B:\n+ai.konduit.se" +
      "rving.vertx.protocols.grpc.apiB\013GrpcServ" +
      "iceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.konduit.serving.pipeline.impl.data.protobuf.DataProtoMessage.getDescriptor(),
        }, assigner);
    ai.konduit.serving.pipeline.impl.data.protobuf.DataProtoMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
