{
 "title": "Pipeline Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memoryuse_pipelines_12cdacbcac68"
    },
    {
     "expr": "cpu_0_memavailable0_pipelines_12cdacbcac68"
    },
    {
     "expr": "cpu_1_memavailable1_pipelines_12cdacbcac68"
    },
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "Inference Time (ETL/Inference)",
   "type": "graph",
   "description": "ETL and Inference Execution Time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "inference_seconds_active_count" },
    {
     "expr": "batch_creation_seconds_active_count"
    }
   ]
  },
  {
   "title": "Cpu and System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" },
    { "expr": "system_load_average_1m" },
    {
     "expr": "Cpu_0_load0_pipelines_12cdacbcac68"
    },
    {
     "expr": "Cpu_1_load1_pipelines_12cdacbcac68"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes" },
    {
     "expr": "jvm_gc_memory_allocated_bytes_total"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes"
    },
    { "expr": "jvm_gc_live_data_size_bytes" }
   ]
  }
 ]
}