name: Install protobuf linux
runs:
  using: composite
  steps:
    - name: Install protobuf linux
      shell: bash
      run: |
        curl -fsSL https://github.com/google/protobuf/releases/download/v3.8.0/protobuf-cpp-3.8.0.tar.gz \
                               | tar xz && \
                               cd protobuf-3.8.0 && \
                               ./configure --prefix=/opt/protobuf && \
                               make -j2 && \
                               sudo make install && \
                               cd .. && \
                               rm -rf protobuf-3.8.0
        echo "/opt/protobuf/bin" >> $GITHUB_PATH